name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  application_name: SpotifySongTagger
  updater_name: Updater
  build_config: Release

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # prepare version update
    - name: Extract tag
      uses: olegtarasov/get-tag@v2.1
      id: tagName
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    # update versions locally
    - name: Update application version
      run: python .buildscripts/update_version_csproj.py --tagname ${{ steps.tagName.outputs.tag }} --project-file ${{ env.application_name }}/${{ env.application_name }}.csproj
    - name: Update updater version
      run: python .buildscripts/update_version_csproj.py --tagname ${{ steps.tagName.outputs.tag }} --project-file ${{ env.updater_name }}/${{ env.updater_name }}.csproj
    - name: Update installer version
      run: python .buildscripts/update_version_vdproj.py --tagname ${{ steps.tagName.outputs.tag }} --project-file Setup/Setup.vdproj
    - name: Push updated version number
      uses: test-room-7/action-update-file@v1
      with:
          file-path: |
              ${{ env.application_name }}/${{ env.application_name }}.csproj
              ${{ env.updater_name }}/${{ env.updater_name }}.csproj
              Setup/Setup.vdproj
          commit-msg: Update version number
          github-token: ${{ secrets.GITHUB_TOKEN }}


    # setup runtime
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    # setup msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
    - name: Run python setup test script
      run: python .buildscripts/test.py
    - name: Print VS dir
      run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
    - name: Print VS dir2
      run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE"
    - name: print path
      run: echo %PATH%
    - name: run devenv
      run: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.exe
    
    # publish program to {application_name}/{build_config}
    - name: Publish program
      run: dotnet publish ${{ env.application_name }} --configuration ${{ env.build_config }} -o ${{ env.application_name }}/${{ env.build_config }}
    # publish updater to {application_name}/{build_config}
    - name: Publish updater
      run: dotnet publish ${{ env.updater_name }} --configuration ${{ env.build_config }} -o ${{ env.application_name }}/${{ env.build_config }}
    # publish setup project
    - name: Publish setup
      run: devenv ${{ env.application_name }}.sln /Project Setup/Setup.vdproj /Build ${{ env.build_config }}
    # rename setup.exe
    - name: Rename setup
      run: cd Setup/${{ env.build_config }} && ren setup.exe ${{ env.application_name }}-Installer.exe 
    
    # zip {application_name}/{build_config} into a zip file where the root folder has name {application_name}
    - name: Zip portable build
      uses: papeloto/action-zip@v1
      with:
        files: ${{ env.application_name }}/${{ env.build_config }}
        dest: Releases/${{ env.application_name }}-${{ steps.tagName.outputs.tag }}.zip
        recursive: false

    - name: Release build
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Releases/${{ env.application_name }}-${{ steps.tagName.outputs.tag }}.zip
          Setup/${{ env.build_config }}/${{ env.application_name }}-Installer.exe